language: python

# safelist
branches:
  
  only:
  - master

install:
  - pip install -U pytest
  - pip install numpy

script: pytest autoDiff_test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
