language: python

# safelist
branches:
  
  only:
  - master
  - final_testing


install:
  - pip install pytest-cov
  - pip install codecov
  - pip install -U pytest
  - pip install numpy
  - pip install matplotlib

script: 
  - pytest --cov=./DreamDiff/


after_success:
  - codecov

