language: python

# safelist
branches:
  
  only:
  - master
  - milestone3_aditya


install:
  - pip install pytest-cov
  - pip install codecov
  - pip install -U pytest
  - pip install numpy


script: 
  - pytest --cov=./DreamDiff/
  
after_success:

  - codecov

