language: python

# safelist
branches:
  
  only:
  - master
  - milestone_3_blake

install:
  - pip install -U pytest
  - pip install numpy

script: pytest test_AutoDiff.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
