language: python

# safelist
branches:
  
  only:
  - master


install:
  - pip install pytest-cov
  - pip install codecov
  - pip install -U pytest
  - pip install numpy

script: 
  - pytest --cov=./ad_library/AutoDiff_test.py
  
after_success:

  - codecov

